[[Wasmtime]]
arch = "aarch64"
git-tree-sha1 = "18876a64c0ecb77474450fe028e32b6651223189"
os = "macos"

    [[Wasmtime.download]]
    sha256 = "73f776146f6212bd78ca6ca0e1ffe68e0cf4da067b3ef23665feb7aabe76d7dd"
    url = "https://github.com/JuliaBinaryWrappers/Wasmtime_jll.jl/releases/download/Wasmtime-v24.0.2+0/Wasmtime.v24.0.2.aarch64-apple-darwin.tar.gz"
[[Wasmtime]]
arch = "aarch64"
git-tree-sha1 = "bbbda959b12eec4a9781078c9052723e9201d376"
libc = "glibc"
os = "linux"

    [[Wasmtime.download]]
    sha256 = "f7cd9369c5689b4ac7bea15765756100c2f5a8d8eb67ec2add8ac24ee034c786"
    url = "https://github.com/JuliaBinaryWrappers/Wasmtime_jll.jl/releases/download/Wasmtime-v24.0.2+0/Wasmtime.v24.0.2.aarch64-linux-gnu.tar.gz"
[[Wasmtime]]
arch = "aarch64"
git-tree-sha1 = "cd2d33b745bff261b0c36ee9accd341bb4de2fd9"
libc = "musl"
os = "linux"

    [[Wasmtime.download]]
    sha256 = "02856417804c912682d97b9375eee6208b1548ad8efb3b5afcd6ab96a3f25448"
    url = "https://github.com/JuliaBinaryWrappers/Wasmtime_jll.jl/releases/download/Wasmtime-v24.0.2+0/Wasmtime.v24.0.2.aarch64-linux-musl.tar.gz"
[[Wasmtime]]
arch = "x86_64"
git-tree-sha1 = "9ea3b1674c589d934e91e7742e140f86a07493b3"
os = "macos"

    [[Wasmtime.download]]
    sha256 = "f9b2576e44c4492abfc01c313081894fc27b32fc9b1f26b44c2498d5f3d997ce"
    url = "https://github.com/JuliaBinaryWrappers/Wasmtime_jll.jl/releases/download/Wasmtime-v24.0.2+0/Wasmtime.v24.0.2.x86_64-apple-darwin.tar.gz"
[[Wasmtime]]
arch = "x86_64"
git-tree-sha1 = "4a6db75ba28226a302e79b422c8a6034089f752b"
libc = "glibc"
os = "linux"

    [[Wasmtime.download]]
    sha256 = "3866f394000c102d8d54d01bc8a8501f1b6ec898692c33e41e4952e9f3187235"
    url = "https://github.com/JuliaBinaryWrappers/Wasmtime_jll.jl/releases/download/Wasmtime-v24.0.2+0/Wasmtime.v24.0.2.x86_64-linux-gnu.tar.gz"
[[Wasmtime]]
arch = "x86_64"
git-tree-sha1 = "cbc29b8000fbb3eef085c0a99f147bc599202bd7"
libc = "musl"
os = "linux"

    [[Wasmtime.download]]
    sha256 = "5d7fb3386fabd4aa906b4f1bfab0f6e199a988876404c4181794aac73d8866fa"
    url = "https://github.com/JuliaBinaryWrappers/Wasmtime_jll.jl/releases/download/Wasmtime-v24.0.2+0/Wasmtime.v24.0.2.x86_64-linux-musl.tar.gz"
[[Wasmtime]]
arch = "x86_64"
git-tree-sha1 = "74af083c595b71b09d2f928b7ccb548a5824603f"
os = "freebsd"

    [[Wasmtime.download]]
    sha256 = "6c4e8f2bfe726488b5196879fdb70c83546275be50983f51f535981ab471f98c"
    url = "https://github.com/JuliaBinaryWrappers/Wasmtime_jll.jl/releases/download/Wasmtime-v24.0.2+0/Wasmtime.v24.0.2.x86_64-unknown-freebsd.tar.gz"
[[Wasmtime]]
arch = "x86_64"
git-tree-sha1 = "c823e0d345ae9b91f310232ac43c99bf06c8e572"
os = "windows"

    [[Wasmtime.download]]
    sha256 = "b7a0af2940a5785f51564ca406b236cce2d8bcf509779b2f78a883a6151c67f3"
    url = "https://github.com/JuliaBinaryWrappers/Wasmtime_jll.jl/releases/download/Wasmtime-v24.0.2+0/Wasmtime.v24.0.2.x86_64-w64-mingw32.tar.gz"
