# Autogenerated wrapper script for Wasmtime_jll for x86_64-w64-mingw32
export libwasmtime, wasmtime

JLLWrappers.@generate_wrapper_header("Wasmtime")
JLLWrappers.@declare_library_product(libwasmtime, "libwasmtime.dll")
JLLWrappers.@declare_executable_product(wasmtime)
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_library_product(
        libwasmtime,
        "bin\\libwasmtime.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_executable_product(
        wasmtime,
        "bin\\wasmtime.exe",
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
